language: c

addons:
    apt:
        packages:
            - gperf
            - elfutils
            - zlib1g-dev
            - clang    # scan-build

os:
    - linux
    - osx

compiler:
    - clang
    - gcc

matrix:
    include:
        - os: linux
          compiler: x86_64-w64-mingw32-gcc
          dist: trusty
          sudo: required
          before_install:
              - sudo apt-get -qq update
              - sudo apt-get install -y gcc-mingw-w64-x86-64
          env: HOST="--host=x86_64-w64-mingw32" TEST="test/main.exe"
        - os: linux
          compiler: clang
          env: CFLAGS="-fsanitize=undefined" ASAN_OPTIONS="detect_leaks=0"
        - os: linux
          compiler: clang
          env: CFLAGS="-fsanitize=address -g" ASAN_OPTIONS="detect_leaks=0"
        - os: linux
          compiler: clang
          env: PATH="/usr/bin:$PATH" TEST=analyze

    exclude:
        - os: osx
          compiler: gcc

script:
    - ./autogen.sh
    - ./configure $HOST
    - make
    - make ${TEST:-test}
